import React from 'react';
import { FormattedMessage } from 'react-intl';

function StocksTable() {
    return (
        <>
            <table className="markets_table">
                <thead>
                    <tr>
                        <th>Title</th>
                        <th><FormattedMessage id="tool" defaultMessage="tool" /></th>
                        <th>Country</th>
                        <th>Currency Quotes</th>
                        <th><FormattedMessage id="minPriceChange" defaultMessage="minPriceChange" /></th>
                        <th>Min volume</th>
                        <th>Max volume</th>
                        <th>Max leverage</th>
                        <th>Number of contracts for 1 lot</th>
                        <th><FormattedMessage id="opening" defaultMessage="opening" /></th>
                        <th><FormattedMessage id="closing" defaultMessage="closing" /></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Alcoa Corp</td>
                        <td>AA</td>
                        <td>USA</td>
                        <td>USD</td>
                        <td>0.01</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>Altaba (Yahoo)</td>
                        <td>AABB</td>
                        <td>USA</td>
                        <td>USD</td>
                        <td>0.01</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>Apple Inc</td>
                        <td>AAPL</td>
                        <td>USA</td>
                        <td>USD</td>
                        <td>0.01</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>Admiral Group</td>
                        <td>ADM</td>
                        <td>UK</td>
                        <td>GBP</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>7:15</td>
                        <td>15:15</td>
                    </tr>
                    <tr>
                        <td>Adidas</td>
                        <td>ADS</td>
                        <td>Germany</td>
                        <td>EUR</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>7:15</td>
                        <td>15:15</td>
                    </tr>
                    <tr>
                        <td>American International Group Inc</td>
                        <td>AIG</td>
                        <td>USA</td>
                        <td>USD</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>Airbus Group</td>
                        <td>AIR</td>
                        <td>France</td>
                        <td>EUR</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>Amazon.com Inc</td>
                        <td>AMZN</td>
                        <td>USA</td>
                        <td>USD</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>Tatneft</td>
                        <td>ATAD</td>
                        <td>UK</td>
                        <td>USD</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>Aviva PLC</td>
                        <td>AV</td>
                        <td>UK</td>
                        <td>GBP</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>American Express Company</td>
                        <td>AXP</td>
                        <td>USA</td>
                        <td>USD</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>Boeing Company</td>
                        <td>BA</td>
                        <td>USA</td>
                        <td>USD</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>Bank of America Corporation</td>
                        <td>BAC</td>
                        <td>USA</td>
                        <td>USD</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>Barclays PLC</td>
                        <td>BARC</td>
                        <td>UK</td>
                        <td>GBP</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>British American Tobacco</td>
                        <td>BATS</td>
                        <td>UK</td>
                        <td>GBP</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>Bayer</td>
                        <td>BAYN</td>
                        <td>Germany</td>
                        <td>EUR</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>Bankia</td>
                        <td>BKIA</td>
                        <td>Spain</td>
                        <td>EUR</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>BMW</td>
                        <td>BMW</td>
                        <td>Germany</td>
                        <td>EUR</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>Danone</td>
                        <td>BN</td>
                        <td>France</td>
                        <td>EUR</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>Burberry Group</td>
                        <td>BRBY</td>
                        <td>UK</td>
                        <td>GBP</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>Centrica PLC</td>
                        <td>CAN</td>
                        <td>UK</td>
                        <td>GBP</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>Caterpillar Inc</td>
                        <td>CAT</td>
                        <td>USA</td>
                        <td>USD</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>Severstal</td>
                        <td>CHMF</td>
                        <td>Russia</td>
                        <td>RUB</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>Continental</td>
                        <td>CON</td>
                        <td>Germany</td>
                        <td>EUR</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>Cisco Systems Inc</td>
                        <td>CSCO</td>
                        <td>USA</td>
                        <td>USD</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>Chevron Corporation</td>
                        <td>CVX</td>
                        <td>USA</td>
                        <td>USD</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>EI du Pont de Nemours and Company</td>
                        <td>DD</td>
                        <td>USA</td>
                        <td>USD</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>Walt Disney Company</td>
                        <td>DIS</td>
                        <td>USA</td>
                        <td>USD</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>Deutsche Post</td>
                        <td>DPW</td>
                        <td>Germany</td>
                        <td>EUR</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>Deutsche Telekom</td>
                        <td>DTE</td>
                        <td>Germany</td>
                        <td>EUR</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>eBay Inc</td>
                        <td>EBAY</td>
                        <td>USA</td>
                        <td>USD</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>Freeport-McMoran Copper & Gold Inc</td>
                        <td>FCX</td>
                        <td>USA</td>
                        <td>USD</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>FedEx Corporation</td>
                        <td>FDX</td>
                        <td>USA</td>
                        <td>USD</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>Total</td>
                        <td>FP</td>
                        <td>France</td>
                        <td>EUR</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>Gas Natural SDG</td>
                        <td>GAS</td>
                        <td>Spain</td>
                        <td>EUR</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>Gazprom</td>
                        <td>GAZP</td>
                        <td>Russia</td>
                        <td>RUB</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>General Electric Company</td>
                        <td>GE</td>
                        <td>USA</td>
                        <td>USD</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>Glencore PLC</td>
                        <td>GLEN</td>
                        <td>UK</td>
                        <td>GBP</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>Norilskiy Nickel</td>
                        <td>GMKN</td>
                        <td>Russia</td>
                        <td>RUB</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>Alphabet Inc C</td>
                        <td>GOOG</td>
                        <td>USA</td>
                        <td>USD</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>GlaxoSmitdKline PLC</td>
                        <td>GSK</td>
                        <td>UK</td>
                        <td>GBP</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>tde Goodyear Tire & Rubber Company</td>
                        <td>GT</td>
                        <td>USA</td>
                        <td>USD</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>Halliburton Company</td>
                        <td>HAL</td>
                        <td>USA</td>
                        <td>USD</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>Home Depot Inc</td>
                        <td>HD</td>
                        <td>USA</td>
                        <td>USD</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>Henkel & Co KGaA</td>
                        <td>HEN3</td>
                        <td>Germany</td>
                        <td>EUR</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>HP Inc</td>
                        <td>HPQ</td>
                        <td>USA</td>
                        <td>USD</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>International Business Machines</td>
                        <td>IBM</td>
                        <td>USA</td>
                        <td>USD</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>Intel Corporation</td>
                        <td>INTC</td>
                        <td>USA</td>
                        <td>USD</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>International Paper Company</td>
                        <td>IP</td>
                        <td>USA</td>
                        <td>USD</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>Johnson & Johnson</td>
                        <td>JNJ</td>
                        <td>USA</td>
                        <td>USD</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>JPMorgan Chase & Co</td>
                        <td>JPM</td>
                        <td>USA</td>
                        <td>USD</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>Coca-Cola Company</td>
                        <td>KO</td>
                        <td>USA</td>
                        <td>USD</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>Kraton Performance Polymers</td>
                        <td>KRA</td>
                        <td>USA</td>
                        <td>USD</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>Legal & General Group PLC</td>
                        <td>LGEN</td>
                        <td>UK</td>
                        <td>GBP</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>Lukoil</td>
                        <td>LKOH</td>
                        <td>Russia</td>
                        <td>RUB</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>Lloyds Banking Group PLC</td>
                        <td>LLOY</td>
                        <td>UK</td>
                        <td>GBP</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>Mapfre</td>
                        <td>MAP</td>
                        <td>Spain</td>
                        <td>EUR</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>Moet Henenssy Louis Vuitton</td>
                        <td>MC</td>
                        <td>France</td>
                        <td>EUR</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>McDonalds Corporation</td>
                        <td>MCD</td>
                        <td>USA</td>
                        <td>USD</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>Magnit</td>
                        <td>MGNT</td>
                        <td>UK</td>
                        <td>USD</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>3M Company</td>
                        <td>MMM</td>
                        <td>USA</td>
                        <td>USD</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>Altria Group</td>
                        <td>MO</td>
                        <td>USA</td>
                        <td>USD</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>Merck & Company Inc</td>
                        <td>MRK</td>
                        <td>USA</td>
                        <td>USD</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>Microsoft Corporation</td>
                        <td>MSFT</td>
                        <td>USA</td>
                        <td>USD</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>Mechel preferred</td>
                        <td>MTLRP</td>
                        <td>Russia</td>
                        <td>RUB</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>L'Oreal</td>
                        <td>OR</td>
                        <td>France</td>
                        <td>EUR</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>Oracle Corporation</td>
                        <td>ORCL</td>
                        <td>USA</td>
                        <td>USD</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>PepsiCo Inc</td>
                        <td>PEP</td>
                        <td>USA</td>
                        <td>USD</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>Pfizer Inc</td>
                        <td>PFE</td>
                        <td>USA</td>
                        <td>USD</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>Procter & Gamble Company</td>
                        <td>PG</td>
                        <td>USA</td>
                        <td>USD</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>Polus Zoloto</td>
                        <td>PLZL</td>
                        <td>Russia</td>
                        <td>RUB</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>Prudential PLC</td>
                        <td>PRU</td>
                        <td>UK</td>
                        <td>GBP</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>Qualcomm Incorporated</td>
                        <td>QCOM</td>
                        <td>USA</td>
                        <td>USD</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>Royal Bank of Scotland Group PLC</td>
                        <td>RBS</td>
                        <td>UK</td>
                        <td>GBP</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>Repsol</td>
                        <td>REP</td>
                        <td>Spain</td>
                        <td>EUR</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>Renault</td>
                        <td>RNO</td>
                        <td>France</td>
                        <td>EUR</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>Rosneft</td>
                        <td>ROSN</td>
                        <td>Russia</td>
                        <td>RUB</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>Rolls-Royce Holdings</td>
                        <td>RR</td>
                        <td>UK</td>
                        <td>GBP</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>Rostelecom</td>
                        <td>RTKM</td>
                        <td>Russia</td>
                        <td>RUB</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>Sberbank</td>
                        <td>SBER</td>
                        <td>Russia</td>
                        <td>RUB</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>J Sainsbury PLC</td>
                        <td>SBRY</td>
                        <td>UK</td>
                        <td>GBP</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>Starbucks Corporation</td>
                        <td>SBUX</td>
                        <td>USA</td>
                        <td>USD</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>Gazprom Neft</td>
                        <td>SIBN</td>
                        <td>Russia</td>
                        <td>RUB</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>Siemens</td>
                        <td>SIE</td>
                        <td>Germany</td>
                        <td>EUR</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>Schneider Electric</td>
                        <td>SU</td>
                        <td>France</td>
                        <td>EUR</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>AT&T Inc</td>
                        <td>T</td>
                        <td>USA</td>
                        <td>USD</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>Telefonica SA</td>
                        <td>TEFBM</td>
                        <td>Spain</td>
                        <td>EUR</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>Tesco PLC</td>
                        <td>TSCO</td>
                        <td>UK</td>
                        <td>GBP</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>Tesla</td>
                        <td>TSLA</td>
                        <td>USA</td>
                        <td>USD</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>Peugeot</td>
                        <td>UG</td>
                        <td>France</td>
                        <td>EUR</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>United Parcel Service Inc</td>
                        <td>UPS</td>
                        <td>USA</td>
                        <td>USD</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>Uralkaliy</td>
                        <td>URKA</td>
                        <td>Russia</td>
                        <td>RUB</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>United Technologies Corporation</td>
                        <td>UTX</td>
                        <td>USA</td>
                        <td>USD</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>Visa Inc</td>
                        <td>V</td>
                        <td>USA</td>
                        <td>USD</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>Volkswagen</td>
                        <td>VOW3</td>
                        <td>Germany</td>
                        <td>EUR</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>VTB Bank</td>
                        <td>VTBR</td>
                        <td>Russia</td>
                        <td>RUB</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>Verizon Communications Inc</td>
                        <td>VZ</td>
                        <td>USA</td>
                        <td>USD</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>Wells Fargo & Company</td>
                        <td>WFC</td>
                        <td>USA</td>
                        <td>USD</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>Wal-Mart Stores Inc</td>
                        <td>WMT</td>
                        <td>USA</td>
                        <td>USD</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                    <tr>
                        <td>Exxon Mobil Corporation</td>
                        <td>XOM</td>
                        <td>USA</td>
                        <td>USD</td>
                        <td>0.0001</td>
                        <td>1</td>
                        <td>10000</td>
                        <td>1:50</td>
                        <td>1</td>
                        <td>13:45</td>
                        <td>19:45</td>
                    </tr>
                </tbody>
            </table>
            <div className="table_last text_left">
                *часы закрытия и открытия торгов указаны по UTC+0
            </div>
        </>
    )
}

export default StocksTable;